### ISSUE TITLE
Wardrobe changes require disconnect

### ISSUE THREAD

**Issue by Sighmir** [Sighmir/vrp_barbershop#1]
Wardrobe doesn't change overlay after setting customization so overlay is lost until next login, use of barbershop or death.

**Comment by UtraTM** [comment]
Any news on that bug?

When i dress my police outfit i have green hair and such stuff until relogg

**Comment by Sighmir** [comment]
Haven't had any time now that I am out of my break, please everyone feel free to edit my script and pull fixes and etc. I'd love to work on them, but I just don't have the time right now.

**Comment by Bretty12Qc** [comment]
lscustoms need change 

-- vehicle db
MySQL.createCommand("vRP/lscustoms_columns", [[
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (veh_type varchar(255) NOT NULL DEFAULT 'default') ;
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_plate varchar(255) NOT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_colorprimary varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_colorsecondary varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_pearlescentcolor varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_wheelcolor varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_plateindex varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_neoncolor1 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_neoncolor2 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_neoncolor3 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_windowtint varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_wheeltype varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_mods0 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_mods1 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_mods2 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_mods3 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_mods4 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_mods5 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_mods6 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_mods7 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_mods8 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_mods9 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_mods10 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_mods11 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_mods12 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_mods13 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_mods14 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_mods15 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_mods16 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_turbo varchar(255) NOT NULL DEFAULT 'off');
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_tiresmoke varchar(255) NOT NULL DEFAULT 'off');
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_xenon varchar(255) NOT NULL DEFAULT 'off');
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_mods23 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_mods24 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_neon0 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_neon1 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_neon2 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_neon3 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_bulletproof varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_smokecolor1 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_smokecolor2 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_smokecolor3 varchar(255) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_modvariation varchar(255) NOT NULL DEFAULT 'off');
]])

**Comment by Bretty12Qc** [comment]
dmvschool new table script update 

--[[SQL]]--
MySQL.createCommand("vRP/dmv_column", [[CREATE TABLE IF NOT EXISTS vrp_users (DmvTest varchar(50) NOT NULL default 'Required')]])

**Comment by Bretty12Qc** [comment]
Showroom (server.lua)

-- vehicle db / garage and lscustoms compatibility
MySQL.createCommand("vRP/showroom_columns", [[
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (veh_type varchar(255) NOT NULL DEFAULT 'default') ;
CREATE TABLE IF NOT EXISTS vrp_user_vehicles (vehicle_plate varchar(255) NOT NULL);
]])

**Comment by Sighmir** [comment]
I added a work around for this problem in the form of a button on
https://github.com/Sighmir/vrp_basic_menu the button Fix Haircut is supposed to re-apply your hair color and beard in case it gets messed up.

**Comment by Sighmir** [comment]
Add:

```
TriggerEvent("vRP:cloakroom:update", player)

```
to vRP/module/cloakroom.lua after line 39 and 76 for cloakroom compatibility.
Under data.cloakroom_idle = nil and vRPclient.setCustomization(player,{idle_copy}).

to vRP/module/home_components.lua after line 80 for wardrobe compatibility.
Under vRPclient.setCustomization(player,{custom}).
