### ISSUE TITLE
Incompatibility with cloackroom

### ISSUE THREAD

**Issue by Aleweadan** [Sighmir/vrp_barbershop#5]
There is some incompatibility with cloackroom when you change uniform

**Comment by Sighmir** [comment]
There definitely is. Can't fix now. Maybe in the future.

**Comment by Aleweadan** [comment]
It's related to core ?

**Comment by Sighmir** [comment]
I believe to fix this I'd need to change the core files, but to do that the least possible I will create an event.

**Comment by Aleweadan** [comment]
why not make a core modification of barbershop module and create a pull request on the vRP github ?

**Comment by Sighmir** [comment]
Imagic told us to not modify the core files, and I understand his reasons, I rather make everything into a resource using the tools he gave me and ask him for new tools if I need them, next update he will probably have interfaces to support improvements on a few of my addons. It's cleaner and better that way.

**Comment by Aleweadan** [comment]
ok thank you for explanations !

**Comment by oli0929** [comment]
I looked at you script , i'm not a dev either programmer  (what i mean , maybe i'm wrong) , but it is not a problem linked to the local data by chance who will search the information in your database ? .

**Comment by Sighmir** [comment]
I don't _exactly_ know what you mean, but it's linked to the saved customization data on the user data table, since it saves the hairs without first using something "SetPedHeadBlendData", after doing that, the hair and some other facial features are treated differently, thus conflicting with the data loaded when loading saved outfits or uniforms. 
"SetPedHeadBlendData" is required for beards and other features from Barbershop.
I believe I know how to fix this, but I don't have time at the moment, if no one have fixed it in 3 months, I will get another break and will work on it then.

**Comment by oli0929** [comment]
Finaly , we tested the mod under our server. We realized that it's the client side the bug. I explain, when I take uniform, I lose the overlay with face, hair, beard, etc. but my friend who is logged on the same server as me always sees me with my head that I have modified. at barbershop without problem. Is this a missing trigger event?

**Comment by Sighmir** [comment]
I explained the problem to you already, I will lock this conversation from now on, there's nothing else to be said.

And also, there's not one event in vrp_barbershop, I can't see how that would be the problem...
The problem is explained on my last answer.

**Comment by Sighmir** [comment]
I added a work around for this problem in the form of a button on 
https://github.com/Sighmir/vrp_basic_menu the button Fix Haircut is supposed to re-apply your hair color and beard in case it gets messed up.

**Comment by Sighmir** [comment]
Add:

```
TriggerEvent("vRP:cloakroom:update", player)

```
to vRP/module/cloakroom.lua after line 39 and 76 for cloakroom compatibility.
Under data.cloakroom_idle = nil and vRPclient.setCustomization(player,{idle_copy}).

to vRP/module/home_components.lua after line 80 for wardrobe compatibility.
Under vRPclient.setCustomization(player,{custom}).
