### ISSUE TITLE
Fail to load resource

### ISSUE THREAD

**Issue by bluefir111** [Sighmir/vrp_barbershop#7]
I've been getting a message on my server saying vrp_barbershop has failed to load resource. I checked the __resource and it appears to be missing 2 lines of code to make it work on FX server

**Comment by Sighmir** [comment]
Post the error and the 2 missing lines or I can't help you, I believe this error is only happening on your end, or there would be many errors like this one.

**Comment by bluefir111** [comment]
im getting this error 

Resource loading for vrp_barbershop failed:

Could not open resource metadata file C:/TCAFiles\Users\jasonh\1401/resources//vrp_barbershop/__resource.lua.

**Comment by Sighmir** [comment]
Did you move the vrp_barbershop folder inside your resources folder? You need to have the folder vrp_barbershop, that comes inside the vrp_barbershop-master when you download it from GitHub, inside your resources folder, something must be wrong on the way you installed the resource.

**Comment by bluefir111** [comment]
know what i might of messed up there. bc i have vrp_barbershop inside of another folder of vrp_barbershop. let me go pull it out and fix that and get back to u

**Comment by Sighmir** [comment]
The folder that goes in resources is the folder that have the __resource.lua file inside it.
